# Generated by Django 4.0.3 on 2022-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hpItems',
            fields=[
                ('hpItem', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('hpName', models.CharField(max_length=50)),
                ('hpDescription', models.TextField(max_length=200)),
            ],
        ),
    ]
